server:
  port: 8085
spring:
#  application:
#    name: demo
  mail:
    host: smtp.gmail.com
    port: 587
    username: bujatinaaron@gmail.com
    password: yaayrgjsfjpmcqbq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  jwt:
    secret-key: a25307b04c9aae82fd20b72ceba9e77ac40e8b1f10d7c3b0dcb2ab7d603664a3
    expiration-time: 900000
#  datasource:
#    url: jdbc:postgresql://localhost:5432/dbproduct
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: never

api:
  product:
    base-url: https://fakestoreapi.com
  order:
    base-url:
  user:
    base-url: https://fakestoreapi.com